### ISSUE TITLE
Prendendo o usuário

### ISSUE THREAD

**Issue by mill3na** [milenaalcantara/CalcFi#3]
https://github.com/milenaalcantara/CalcFi/blob/8d3340915e2c91b991e0b0886799c2dcba284148/Sources/CalcFinancing/Todo/CLI.swift#L87-L99

Oi, Mi! Parabéns pelo seu código, foi maravilhoso ler tudo absolutamente limpo, estruturado e separadinho. 
Teu código tá bem funcional, mas acho que fica um pouco abrupto pro usuário escolher essa tabela, a não ser que ele saiba exatamente o que quer (o que na maioria das vezes não acontece...), então uma sugestão que te dou é: que tal colocar uma opção de informações? Assim, caso ele esteja com dúvida, consegue se resolver na própria aplicação (o que deixa o programa bem mais "confortável", digamos assim, e o usuário tende a usar mais vezes o programa).

Se precisar de algo, conta comigo! :)

**Comment by milenaalcantara** [comment]
Olá, mi 👋🏻

Normalmente o usuário já possui todas essas informações, mas tem razão, pode ser que algum usuário saiba a tabela mas não saiba o que essa tabela significa. 
Coloquei uma pequena descrição no print, espero que seja minimamente suficiente, confere lá. Qualquer coisa pode falar de novo. 

Ty ❤️
